version: "3.9"

volumes:
  keyfile:
  data1:
  data2:
  data3:
  data4:

networks:
  common-network:
    driver: bridge
    # ipam:
      # driver: default
      # config:
      #   - subnet: 172.10.5.0/24

services:

  blt-mongo-keys:
    image: depop/openssl-bats
    volumes:
      - ./keyfile:/mongo-conf
    command: 'bash -c "openssl rand -base64 741 > /mongo-conf/mongodb-keyfile; chmod 600 /mongo-conf/mongodb-keyfile; chown 999 /mongo-conf/mongodb-keyfile"'

  mongo-setup:
    container_name: mongo-setup
    image: mongo
    restart: on-failure
    networks:
      - common-network
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ] # Make sure this file exists (see below for the setup.sh)
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - mongo4

  # Primary
  mongo1:
    image: mongo:latest
    container_name: mongo1
    volumes:
      - ./keyfile:/opt/keyfile
      - ./data1:/data/db
    env_file: 
      - mongod.env
    # environment:
      # - MONGODB_REPLICA_SET_MODE=primary
      # - MONGODB_PRIMARY_PORT_NUMBER=27017
      # - MONGO_INITDB_ROOT_USERNAME=catalog
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGODB_REPLICA_SET_KEY=rs0
    ports:
      - 27017:27017
    command: 'mongod  --auth --keyFile /opt/keyfile/mongodb-keyfile --journal --bind_ip_all --replSet rs0'
    depends_on:
        - blt-mongo-keys
    networks:
      - common-network
  
  # Worker 1
  mongo2:
    image: mongo:latest
    container_name: mongo2
    volumes:
      - ./keyfile:/opt/keyfile
      - ./data2:/data/db
    env_file: 
      - mongod.env      
    # environment:
      # - MONGODB_REPLICA_SET_MODE=secondary
      # - MONGODB_PRIMARY_HOST=mongo1
      # - MONGODB_PRIMARY_PORT_NUMBER=27017
      # - MONGO_INITDB_ROOT_USERNAME=catalog
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGODB_REPLICA_SET_KEY=rs0
    ports:
      - 27018:27017
    command: 'mongod  --auth --keyFile /opt/keyfile/mongodb-keyfile --journal --bind_ip_all  --replSet rs0'
    depends_on:
        - blt-mongo-keys
        - mongo1
    networks:
      - common-network
  
  # Worker 2
  mongo3:
    image: mongo:latest
    container_name: mongo3
    volumes:
      - ./keyfile:/opt/keyfile
      - ./data3:/data/db
    env_file: 
      - mongod.env
      # environment:
      # - MONGODB_REPLICA_SET_MODE=secondary
      # - MONGODB_PRIMARY_HOST=mongo1
      # - MONGODB_PRIMARY_PORT_NUMBER=27017
      # - MONGO_INITDB_ROOT_USERNAME=catalog
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGODB_REPLICA_SET_KEY=rs0
    ports:
      - 27019:27017
    command: 'mongod  --auth --keyFile /opt/keyfile/mongodb-keyfile  --journal --bind_ip_all --replSet rs0'
    depends_on:
        - blt-mongo-keys
        - mongo1
    networks:
      - common-network
  
  # Worker 3
  mongo4:
    image: mongo:latest
    container_name: mongo4
    volumes:
      - ./keyfile:/opt/keyfile
      - ./data4:/data/db
    env_file: 
      - mongod.env    
      # environment:
      # - MONGODB_REPLICA_SET_MODE=secondary
      # - MONGODB_PRIMARY_HOST=mongo1
      # - MONGODB_PRIMARY_PORT_NUMBER=27017
      # - MONGO_INITDB_ROOT_USERNAME=catalog
      # - MONGO_INITDB_ROOT_PASSWORD=123456
      # - MONGODB_REPLICA_SET_KEY=rs0
    ports:
      - 27020:27017
    command: 'mongod  --auth --keyFile /opt/keyfile/mongodb-keyfile --journal --bind_ip_all --replSet rs0'
    depends_on:
        - blt-mongo-keys
        - mongo1
    networks:
      - common-network

  # adminmongo:
  #   image: mrvautin/adminmongo
  #   ports:
  #     - 1234:1234
  #   environment:
  #     - HOST=0.0.0.0
